### ISSUE TITLE
Prevent OrthoList from scrambling orthography

### ISSUE THREAD

**Issue by thetacola** [thetacola/Susquehanna#17]
Currently, the OrthoList's sorting scrambles the orthography somewhat. Not scrambling the orthography would be ideal.

**Comment by alexdcramer** [comment]
It appears this is not a problem with the data itself like I originally feared, but instead a display issue. What appears to be happening is that, when sorting in the OrthoView, the phoneme column is properly sorted by size, however the grapheme column is not updated to match.
