### ISSUE TITLE
Add ability to report bugs to oijon.net from inside the application

### ISSUE THREAD

**Issue by thetacola** [thetacola/Susquehanna#3]
Currently, the report bug feature does not work due to GitHub's forced 2FA. Replacing this with something that can automatically create forum posts on oijon.net would be preferable.

**Comment by alexdcramer** [comment]
Should be noted: reporting through Susquehanna now works, as 2FA works with embedded browsers now

**Comment by thetacola** [comment]
Having bug reports in two different, unlinked places seems like a rather poor idea, especially when GitHub now allows 2FA in embedded browsers. Closing for now, may open back up in the future.
